### ISSUE TITLE
Old web page of unitaryhack can be mistaken for the new unitaryhack.dev page

### ISSUE THREAD

**Issue by andreamari** [unitaryfoundation/unitaryhack2021#58]
This repository is for the 2021 edition of unitaryhack: [unitaryfund.github.io/unitaryhack/](https://unitaryfund.github.io/unitaryhack/)
If I google _unitaryhack_ the first page that I get is this one instead of the new one. This can be confusing to participants, especially since the year is not very visible in the 2021 page.

Any idea how fix this problem? E.g. adding a big text comment, automatically redirect, temporarily close, etc.

@natestemen, @nathanshammah

**Comment by natestemen** [comment]
I see there being two courses of action:
1. Remove the GitHub pages deployment setup (this can be done easily on GitHub under the settings for this repo), and archive[^1] the repo. This is definitely the easiest way, with no future management required.
2. Change the GitHub pages deployment so that this website is deployed to a subdomain of `unitaryhack.dev` such as `2021.unitaryhack.dev` for archival purposes. This should be straightforward following the [docs](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site). Once the new site is deployed to a URL that indicates it is not the canonical location to find information on the current unitaryhack, the repo can be archived[^2] so no future changes can be made (which adds another indication this is not up to date). This solution should hopefully require no maintenance, but it _could_. 

I think both options are fine, but I do like keeping webpages up. I'm happy to take care of this, but if we decide on option 2, I will need access to the UF domains so I can add the appropriate DNS records.


[^1]: This is what Xanadu does. See e.g., 2021 qhack: https://github.com/XanaduAI/QHack2021 and 2022 qhack: https://github.com/XanaduAI/QHack.

[^2]: I couldn't find much online as to whether GitHub pages continues to run once the repo has been archived, but this [community post](https://github.community/t/archiving-a-website/11041) indicates that it does.

**Comment by andreamari** [comment]
During the last Mitiq call, @nathanshammah suggested to add a comment in the home page of the 2021 site with a link to the new site. 
I think this is a simple but quick fix that we can always combine it with more advanced solutions in a second moment.

**Comment by natestemen** [comment]
Agreed, a banner here across all pages is a good start.

I also think putting this site under a subdomain of unitaryhack.dev is quite simple as per the docs I shared in the previous comment.

**Comment by nathanshammah** [comment]
- 1. To get started, I opened a PR for the readme #59. 
- 2. If someone (@francespoblete @natestemen or @WrathfulSpatula for example) could add a banner in the old website, is also a good quick fix to follow up with. 
-  3. @natestemen, I like your idea of a subdomain on the new website (under /2021).

**Comment by crazy4pi314** [comment]
Looks like this is addressed, thanks @natestemen!
